### ISSUE TITLE
Thank you for amazing project... just small nitpick

### ISSUE THREAD

**Issue by Mlocik97** [capelski/express-typed-api#1]
Can we remove this line? I guess you forgot it here when you were testing it:

https://github.com/capelski/express-typed-api/blob/a6ac881ceb37ef57310e0e270d89c24269221bfa/projects/%40express-typed-api/common/source/request-types-server.ts#L65

**Comment by capelski** [comment]
@Mlocik97 Good spot! I've removed the line via [19be9dc](https://github.com/capelski/express-typed-api/commit/19be9dc2de9053d6956c1aeb269273a2314bc872) and published a new version (1.0.8) to npm 👍

If you like this project, I'd recommend you to have a look at [typed-web-api](https://github.com/capelski/typed-web-api). It's the same concept but it is more generic, so it can support other frameworks (e.g. [NestJS](https://nestjs.com/)).

**Comment by capelski** [comment]
@Mlocik97 Good spot! I've removed the line via [19be9dc](https://github.com/capelski/express-typed-api/commit/19be9dc2de9053d6956c1aeb269273a2314bc872) and published a new version (1.0.8) to npm 👍

If you like this project, I'd recommend you to have a look at [typed-web-api](https://github.com/capelski/typed-web-api). It's the same concept but it is more generic, so it can support other frameworks (e.g. [NestJS](https://nestjs.com/)).
